query Input {
  cart {
    lines {
      id
      cost {
        subtotalAmount {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            # Identify whether this product belongs to “Premium” or “Featured” collections by checking for the presence of specific tags.
            # title
            inPremiumCollection: hasAnyTag(tags: ["premium"])
            inFeaturedCollection: hasAnyTag(tags: ["featured"])
          }
        }
      }
    }
  }
  discount {
    discountClasses
  }
}
