api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "cross-collection-bundle"
type = "function"
uid = "0ddc8e9d-7a49-5e36-c3b9-1ecc1edb4f9b674f1bba"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/cross-collection-bundle.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
